"""Add connection_id to reports

Revision ID: 0909e9269c07
Revises: d18fa7a72098
Create Date: 2025-07-29 14:12:45.243384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0909e9269c07'
down_revision: Union[str, Sequence[str], None] = 'd18fa7a72098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('connection_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reports', 'db_connections', ['connection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_column('reports', 'connection_id')
    # ### end Alembic commands ###
