"""empty message

Revision ID: 6e3afa794bff
Revises: a9ca19f92b71
Create Date: 2025-08-11 00:01:29.698176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e3afa794bff'
down_revision: Union[str, Sequence[str], None] = 'a9ca19f92b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('chat_sessions', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'title')
    op.drop_column('chat_sessions', 'last_updated')
    # ### end Alembic commands ###
