"""Add usage counters to User model

Revision ID: 7183918fb58f
Revises: 0212793aed6e
Create Date: 2025-08-10 15:20:44.451165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7183918fb58f'
down_revision: Union[str, Sequence[str], None] = '0212793aed6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('messages_used', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('reports_used', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reports_used')
    op.drop_column('users', 'messages_used')
    # ### end Alembic commands ###
