"""Add relationships for Report and Feedback models

Revision ID: bb9e748504be
Revises: f7c28a33957c
Create Date: 2025-07-18 22:32:37.538023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb9e748504be'
down_revision: Union[str, Sequence[str], None] = 'f7c28a33957c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('useful_sections', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_feedbacks_id'), 'report_feedbacks', ['id'], unique=False)
    op.add_column('reports', sa.Column('results', sa.JSON(), nullable=True))
    op.drop_column('reports', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('content', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('reports', 'results')
    op.drop_index(op.f('ix_report_feedbacks_id'), table_name='report_feedbacks')
    op.drop_table('report_feedbacks')
    # ### end Alembic commands ###
