"""empty message

Revision ID: d18fa7a72098
Revises: 70a1641a93e6
Create Date: 2025-07-25 12:24:24.316545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd18fa7a72098'
down_revision: Union[str, Sequence[str], None] = '70a1641a93e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_connections', sa.Column('alias', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_connections', 'alias')
    # ### end Alembic commands ###
