"""empty message

Revision ID: d5bebce82d6b
Revises: 6e3afa794bff
Create Date: 2025-08-17 19:12:50.381084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5bebce82d6b'
down_revision: Union[str, Sequence[str], None] = '6e3afa794bff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vk_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_vk_id'), 'users', ['vk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_vk_id'), table_name='users')
    op.drop_column('users', 'vk_id')
    # ### end Alembic commands ###
