"""empty message

Revision ID: e746118c9ff8
Revises: b4a43406220e
Create Date: 2025-08-19 12:56:43.497855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e746118c9ff8'
down_revision: Union[str, Sequence[str], None] = 'b4a43406220e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('platform_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_users_platform_id'), 'users', ['platform_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_platform_id'), table_name='users')
    op.drop_column('users', 'platform_id')
    # ### end Alembic commands ###
